### ISSUE TITLE
Getting data from Reddit

### ISSUE THREAD

**Issue by crackheadakira** [stirante/facaccimo#3]
I'm trying to use the Parse Reddit Post option but it seems to be stuck on **"Getting data from Reddit**

**Comment by crackheadakira** [comment]
i think it was just because i tried right after the reddit post was made. tried adding it again later and it worked

**Comment by stirante** [comment]
Again, I'm gonna add something to make it not stuck on error and just tell the user to try again. Though I'm gonna do it tomorrow, because it's 11pm here.

**Comment by crackheadakira** [comment]
same here

**Comment by crackheadakira** [comment]
a bit related to this topic.

Would it be possible to make it so you can put two different urls in at the same time and it would fetch the images? Because currently it isn't possible

**Comment by stirante** [comment]
Yes, it's possible. I'm gonna work on it now.

**Comment by stirante** [comment]
Fixed in https://github.com/stirante/facaccimo/commit/faa3a5e722eac618c24c6ddde0fbc5efc675ad6a

Also added a way to parse multiple Reddit URLs. Just paste multiple URLs into text box with every URL in another line.

Btw every time I update facaccimo, you might need to force refresh the site with `Ctrl+F5`
